DROP DATABASE IF EXISTS `pa-rattrapage`;

CREATE DATABASE `pa-rattrapage` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS USERS(
      id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      email VARCHAR(50) NOT NULL
) ENGINE = InnoDB;
